# This workflow uses actions to automatically run the NGA - Gauge/Flood Monitoring
# script.

name: floodscan-download

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # Run every day at 10 pm
jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'
      - uses: r-lib/actions/setup-pandoc@v2

      # - name: Install System Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       libxml2-dev \
      #       libgdal-dev \
      #       libproj-dev \
      #       libgeos-dev \
      #       libudunits2-dev

      - name: Create authorization JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "auth.json"
          json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Cache R dependencies
        id: cache-r-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: R-dependency-cache-${{ hashFiles('.github/depends.R') }}

      - name: Install R dependencies
        if: steps.cache-r-deps.outputs.cache-hit != 'true'
        run: |
          Rscript .github/depends.R

      # - name: Run floodscan-download
      #   run: |
      #     source(file.path("src", "DL_zips.R"))
      #   shell: Rscript {0}
      #   env:
      #     GFF_JSON: "sa_auth.json"
      #     FLOODSCAN_SFED_URL: ${{ secrets.FLOODSCAN_SFED_URL }}
      #     FLOODSCAN_MFED_URL: ${{ secrets.FLOODSCAN_MFED_URL }}
